### ISSUE TITLE
IOS simulator❓ 

### ISSUE THREAD

**Issue by frankbolviken** [cuvent/react-native-vision-camera#1035] opened 2022-05-10 07:40 UTC
### Question

Libraries like react-native-camera etc still have an option of taking a dummy photo when used on simulator (just a black image). This library the camera does not show, breaking the flow of our app where we have to take a photo to confirm a delivery. This makes testing on the simulator a pain. Is there any way of having this functionality when used on iOS simulator? For instance by just showing a black screen with a "take photo" button.

### VisionCamera Version

2.13.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment] 2022-05-10 08:43
Hi, this is a duplicate of https://github.com/mrousavy/react-native-vision-camera/issues/437. Adding support for that isn't easy, especially when we want to support video recordings or frame processors as well. I'll gladly accept any PRs that add support for this, but I personally don't need this feature in my apps, hence I didn't build it :)

**Closed as completed by mrousavy** 2022-05-10 08:43 UTC
Labels: 💭 question
