### ISSUE TITLE
Is there a way to turn off capture sound❓ 

### ISSUE THREAD

**Issue by PABourdais** [cuvent/react-native-vision-camera#713] opened 2022-01-04 12:56 UTC
### Question

Is there a way to turn off capture sound when pictures is taken ?

### What I tried

I know that it was possible on react-native-camera

### VisionCamera Version

2.11.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment] 2022-01-04 13:26
Hi! Does it make a sound on Android?

**Comment by mrousavy** [comment] 2022-01-04 13:27
Also, duplicate of #713. Let's continue the discussion over there

**Closed as completed by mrousavy** 2022-01-04 13:27 UTC
Labels: 💭 question

**Comment by mrousavy** [comment] 2023-08-21 13:20
Hey! I just implemented this in V3! :) https://github.com/mrousavy/react-native-vision-camera/pull/1702
