### ISSUE TITLE
🐛 react-native-vision-camera undefined.

### ISSUE THREAD

**Issue by Urja99** [cuvent/react-native-vision-camera#2758] opened 2024-04-19 12:21 UTC
### What's happening?

t not working with my library

### Reproduceable Code

```tsx
const requestCameraPermission = useCallback(async () => {
    console.log('Requesting camera permission...');
    const permission = await Camera.getCameraPermissionStatus();
    console.log(`Camera permission status: ${permission}`);

    if (permission === 'denied') {await Linking.openSettings();}
  }, []);
  const devices = useCameraDevices();
  const device = devices.back;
  console.log(devices);

 "react": "18.2.0",
  "react-native": "0.71.8",
  "react-native-vision-camera":"2.16.8"
```

### Relevant log output

```shell
LOG  cameraPermission undefined
 LOG  {"back": undefined, "external": undefined, "front": undefined, "unspecified": undefined}
```

### Camera Device

```json
{"_h": 0, "_i": 0, "_j": null, "_k": null}
```

### Device

samsung s21

### VisionCamera Version

2.16.8

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment] 2024-04-21 21:49
no repro, no **native** logs, not reproduced in example app - closing issue because of lack of information.

**Closed as not planned by mrousavy** 2024-04-21 21:49 UTC
Labels: 🐛 bug
