### ISSUE TITLE
🐛 Camera Preview is Stretched on ShadowLens App on a Samsung J6 (Android 10)

### ISSUE THREAD

**Issue by MaximeDemurger** [cuvent/react-native-vision-camera#2936] opened 2024-06-04 13:20 UTC
### What's happening?

When I open the latest version of ShadowLens on a Samsung J6, the camera image is stretched.

The Samsung J6 is on Android 10 with OneUI 2.0.

I have tried to solve that issue in an app I'm working on and I'm experiencing the same problem.
Even if i add the option `videoAspectRatio` or `photoAspectRatio` to the formatFilter with the `useCameraFormat`, it still doesn't solve the issue.

https://github.com/mrousavy/react-native-vision-camera/assets/60433883/44234bce-15b0-4773-90bf-c8062bc9f734

### Reproduceable Code

```tsx
ShadowLens App
```

### Relevant log output

```shell
Can't access
```

### Camera Device

```json
Can't access
```

### Device

Samsung J6 (Android 10)

### VisionCamera Version

^4.0.0

### Can you reproduce this issue in the VisionCamera Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment] 2024-06-13 15:40
Thanks for reporting! I just released a new update to Google Play (in review right now) that'll fix this I think.

I'll close this for now, can you please test tomorrow or something when the new update is out to double-check if the issue is really fixed?

For me on my Samsung it looks correct now.

Thanks!

**Closed as completed by mrousavy** 2024-06-13 15:40 UTC
Labels: 🐛 bug
