### ISSUE TITLE
App crashes after installation  react-native-vision-camera🐛 

### ISSUE THREAD

**Issue by alenseferovic1** [cuvent/react-native-vision-camera#756] opened 2022-01-19 08:04 UTC
### What were you trying to do?

Hi, I want to replace current react-native-camera package with this by suggestion of the author https://github.com/react-native-camera/react-native-camera package.

After installation I'm trying to run my app but app crashes. I have checked troubleshooting in documentation https://mrousavy.com/react-native-vision-camera/docs/guides/troubleshooting and everything is okay. If I comment this two method from the image below I can run my app.

<img width="685" alt="Screenshot 2022-01-19 at 08 51 36" src="https://user-images.githubusercontent.com/17699453/150088067-e187f82d-9185-409e-badf-3b56d2d86ff9.png">

<img width="673" alt="Screenshot 2022-01-19 at 08 51 21" src="https://user-images.githubusercontent.com/17699453/150088147-b8632735-1e90-4f75-ab09-198940f85fb3.png">
 

### What happened instead?

After installation I'm trying to run my app but app crashes.

### Device

iPhone 12, iPhone 8

### VisionCamera Version

2.12.0

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment] 2022-01-19 08:43
Your app doesn't _crash_, it fails to _build_.

Duplicate of #716, seems to be related to your Xcode version. I currently don't have that error on my end, running Xcode 13.2.1 (13C100)

**Closed as completed by mrousavy** 2022-01-19 08:43 UTC
Labels: 🐛 bug
