### ISSUE TITLE
🐛 We are configure ITF type for codeScanner but not read the following type.

### ISSUE THREAD

**Issue by sathiyaraj45** [cuvent/react-native-vision-camera#2089] opened 2023-10-26 11:45 UTC
### What's happening?

The ITF (Interleaved 2 of 5) is a one-dimensional barcodes that encode two numerical characters for every five bars. 

Here I'm unable to attach the image so I gave the barcode generate url details.

I used the following site to generate the bar code:
https://scanbot.io/barcode-generator/itf/
value is : 0176626522 

We unable to capture the barcode for this type. Could you advise what wrong things I missed to implement. 

### Reproduceable Code

```tsx
const codeScanner: CodeScanner = {
    codeTypes: ['itf'],
    onCodeScanned: (codes) => {
      setCameraSatus(false);
      console.log(`Scanned ${codes.length} codes!`)
      console.log('Scan result');
      console.log(codes);
    }
  }
```

### Relevant log output

```shell
2023-10-26 15:38:46.643741+0400 CamscanApp_v3[3793:525502] [connection] nw_socket_handle_socket_event [C15.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:38:49.720275+0400 CamscanApp_v3[3793:525502] [connection] nw_socket_handle_socket_event [C16.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:38:52.767776+0400 CamscanApp_v3[3793:525466] [connection] nw_socket_handle_socket_event [C17.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:38:55.865132+0400 CamscanApp_v3[3793:525500] [connection] nw_socket_handle_socket_event [C18.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:38:58.936539+0400 CamscanApp_v3[3793:525500] [connection] nw_socket_handle_socket_event [C19.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:39:01.975366+0400 CamscanApp_v3[3793:525466] [connection] nw_socket_handle_socket_event [C20.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:39:05.046600+0400 CamscanApp_v3[3793:525502] [connection] nw_socket_handle_socket_event [C21.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
2023-10-26 15:39:08.078647+0400 CamscanApp_v3[3793:525402] [connection] nw_socket_handle_socket_event [C22.1.1:1] Socket SO_ERROR [54: Connection reset by peer]
```

### Camera Device

```json
const codeScanner: CodeScanner = {
    codeTypes: ['itf'],
    onCodeScanned: (codes) => {
      setCameraSatus(false);
      console.log(`Scanned ${codes.length} codes!`)
      console.log('Scan result');
      console.log(codes);
    }
  }
```

### Device

iPad Generation 6

### VisionCamera Version

3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

No, I cannot reproduce the issue in the Example app

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by lucca180** [comment] 2023-10-27 14:10
duplicate of #2064

**Closed as completed** 2023-10-31 13:39 UTC
Labels: 🐛 bug
