### ISSUE TITLE
🐛 react-native-vision-camera Crash on MI and Realme Phone

### ISSUE THREAD

**Issue by msen04377** [cuvent/react-native-vision-camera#1248] opened 2022-09-17 11:56 UTC
### What were you trying to do?

                      <>
                        <Camera
                          ref={camera}
                          device={device}
                          style={StyleSheet.absoluteFill}
                          isActive={true}
                          video={true}
                          audio={true} />
                      </>

### Reproduceable Code

```tsx
<>
                        <Camera
                          ref={camera}
                          device={device}
                          style={StyleSheet.absoluteFill}
                          isActive={true}
                          video={true}
                          audio={true} />
                      </>

if i am doing isActive = true then it is crashed when i am recording the video in MI and REALME phone althought other phone like samsung , oppo it is working fine.
```

### What happened instead?

No error getting , even i am applying adb logcat but no any i am getting

### Device

RMX3085 Realme 8

### VisionCamera Version

2.14.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by hasnainbaloch** [comment] 2022-09-17 13:03
Facing same issue any solution?

**Comment by hasnainbaloch** [comment] 2022-09-17 18:51
java.lang.IllegalStateException: Surface was requested when the Recorder had encountered error androidx.camera.video.internal.ResourceCreationException: androidx.camera.video.internal.encoder.InvalidConfigException
.
.
.

**Comment by hasnainbaloch** [comment] 2022-09-17 18:53
Camera was working fine before the new **Android** update and this package is still working fine in **IOS**

**Comment by zzz08900** [comment] 2022-10-01 19:19
> Camera was working fine before the new **Android** update and this package is still working fine in **IOS**

Mind to elaborate what  "new Android update" are we talking about here? Update from Android 11 to 12 or just some random OTA patch issued by phone manufacturers?

**Comment by xeroxoid** [comment] 2023-01-24 11:23
Possible duplicate of #907 (solution inside)

**Comment by mrousavy** [comment] 2023-09-30 09:42
Closing as this is a stale issue - this might have been fixed with the full rewrite in VisionCamera V3 (🥳) - if not, please create a new issue.

**Closed as completed by mrousavy** 2023-09-30 09:42 UTC
Labels: 🐛 bug
