### ISSUE TITLE
Camera cannot survive after screen off/on❓ 

### ISSUE THREAD

**Issue by ontheway16** [cuvent/react-native-vision-camera#2445] opened 2024-01-27 13:18 UTC
### Question

Camera cannot survive, From a react native Android app.

### What I tried

Hi, I am not a developer. I am using a React Native Android app created by some dev., some time ago. Vision camera is used in the app, to capture qr code.
A problem suddenly developed and I am trying to figure out if it's my phone, or something wrong with code.
When I open qr code scanner and start live qr code scanning, it's all fine.
After a scan, I am turning off phone screen using physical button, to preserve battery. If I turn it on under a minute, in most cases, no problems.
If I keep it off a minute or longer, when I open phone screen, the camera is black, like it did not come up from sleep or whatever mode. Sometimes this happens immediately after closing phone screen and open, sometimes, after a couple mins later.
Do anyone of you experienced such an issue?
Thank you for any guidance.

### VisionCamera Version

V2

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment] 2024-01-29 12:40
Hey - thanks for reporting this, but two things:

1. This is a question, not a bug report. I am missing all kinds of relevant information for this like logs or traces.
2. I will not work on any bug fixes or improvements for VisionCamera V2 anymore, this has likely been fixed in V3 (full rewrite)

**Closed as completed by mrousavy** 2024-01-29 12:40 UTC
Labels: 💭 question
