### ISSUE TITLE
🐛Camera showing black screen on first render. both Android and iOS

### ISSUE THREAD

**Issue by anuragkaushik10** [cuvent/react-native-vision-camera#2362] opened 2024-01-09 09:02 UTC
### What's happening?

When i am trying to open camera for the first time its, showing black screen.

### Reproduceable Code

```tsx
<Camera
        style={stylesWithTheme.camera}
        device={device}
        isActive={isFocused}
        audio={false}
        codeScanner={codeScanner}
      />
```

### Relevant log output

```shell
2024-01-09T08:51:50.679Z
419
Camera3-Device
Set real time priority for request queue thread (tid 11343)
2024-01-09T08:51:50.681Z
11072
CreateCaptureSession
Camera 10: Capture Session #1005 closed!
2024-01-09T08:51:50.681Z
11072
CreateCaptureSession
Camera 10: Capture Session #1006 configured!
2024-01-09T08:51:50.682Z
11072
CameraSession
Successfully configured Session with 1 outputs for Camera #10!
2024-01-09T08:51:50.682Z
11072
CameraSession
Preview Output is null, aborting...
2024-01-09T08:51:50.682Z
11072
CameraSession
Successfully updated CameraSession Configuration! isActive: true
2024-01-09T08:51:50.682Z
11072
CameraView
invokeOnInitialized()
2024-01-09T08:51:50.684Z
11072
CameraView
invokeOnStarted()
2024-01-09T08:51:50.690Z
11072
CameraSession
Configuring Session for Camera #10...
2024-01-09T08:51:50.690Z
11072
SurfaceOutput
Closing BarcodeScanner..
2024-01-09T08:51:50.692Z
11072
CameraSession
Adding 1280 x 960 Preview Output...
2024-01-09T08:51:50.692Z
11072
PreviewView
Resizing PreviewView to 1280 x 960...
2024-01-09T08:51:50.693Z
11072
CameraSession
Adding 1280 x 720 CodeScanner Output in Format #35...
2024-01-09T08:51:50.694Z
11072
DynamiteModule
Local module descriptor class for com.google.mlkit.dynamite.barcode not found.
2024-01-09T08:51:50.695Z
11072
CreateCaptureSession
Camera 10: Creating Capture Session #1007... Hardware Level: 0} | Outputs: [android.hardware.camera2.params.OutputConfiguration@8123dd3e, android.hardware.camera2.params.OutputConfiguration@fef8f62b]
2024-01-09T08:51:50.695Z
11072
CreateCaptureSession
Using new API (>=28)
2024-01-09T08:51:50.696Z
419
cameraserver
createSurfaceFromGbp: Camera 10 with consumer usage flag: 2304: Forcing asynchronous mode forstream
2024-01-09T08:51:50.696Z
419
cameraserver
createSurfaceFromGbp: Camera 10: Overriding format 0x4 to IMPLEMENTATION_DEFINED
2024-01-09T08:51:50.699Z
358
camera.provider.ranchu
CameraDeviceSession:configureStreams:176 cfg={ .streams.size=2, .operationMode=0, .cfg.sessionParams.size()=64,  .streamConfigCounter=2, .multiResolutionInputImage=false }
2024-01-09T08:51:50.699Z
358
camera.provider.ranchu
CameraDeviceSession:configureStreams:199 stream={ .id=1, .streamType=0, .width=1280, .height=960, .format=IMPLEMENTATION_DEFINED, .usage=0x900, .dataSpace={ .low=0x0, .s=0, .t=0, .r=0 }, .rotation=0, .physicalCameraId='', .bufferSize=0, .groupId=-1, .dynamicRangeProfile=0x1 }
2024-01-09T08:51:50.699Z
358
camera.provider.ranchu
CameraDeviceSession:configureStreams:199 stream={ .id=2, .streamType=0, .width=1280, .height=720, .format=YCBCR_420_888, .usage=0x3, .dataSpace={ .low=0x0, .s=2, .t=3, .r=1 }, .rotation=0, .physicalCameraId='', .bufferSize=0, .groupId=-1, .dynamicRangeProfile=0x1 }
2024-01-09T08:51:50.701Z
419
Camera3-Device
Set real time priority for request queue thread (tid 11343)
2024-01-09T08:51:50.702Z
11072
BpBinder
onLastStrongRef automatically unlinking death recipients: 
2024-01-09T08:51:50.702Z
11072
CreateCaptureSession
Camera 10: Capture Session #1007 configured!
2024-01-09T08:51:50.702Z
11072
CreateCaptureSession
Camera 10: Capture Session #1006 closed!
2024-01-09T08:51:50.702Z
11072
CameraSession
Successfully configured Session with 2 outputs for Camera #10!
2024-01-09T08:51:50.702Z
11072
CameraSession
Successfully updated CameraSession Configuration! isActive: false
```

### Camera Device

```json
  "formats": [],
  "sensorOrientation": "landscape-right",
  "hardwareLevel": "limited",
  "maxZoom": 1,
  "minZoom": 1,
  "maxExposure": 12,
  "supportsLowLightBoost": false,
  "neutralZoom": 1,
  "physicalDevices": [
    "ultra-wide-angle-camera"
  ],
  "supportsFocus": true,
  "supportsRawCapture": false,
  "isMultiCam": false,
  "minExposure": -12,
  "name": "BACK (10)",
  "hasFlash": false,
  "hasTorch": false,
  "position": "back",
  "id": "10"
}
```

### Device

Pixel_5_API34

### VisionCamera Version

^3.6.4

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [ ] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by maksimLobachevskiy** [comment] 2024-01-09 09:16
According to the last release notes Black screen should be already resolved in v 3.7.0.

**Comment by amiransari8921** [comment] 2024-01-09 12:45
getting the same black screen not rendering the camera in first render !
on version react-native-vision-camera 
3.6.17

**Comment by GolliAch** [comment] 2024-01-09 19:32
@maksimLobachevskiy  v 3.7.0. Didn't solve it for us

**Comment by anuragkaushik10** [comment] 2024-01-10 07:53
> According to the last release notes Black screen should be already resolved in v 3.7.0.

Working fine for Android, but not fixed for iOS.

**Comment by alexandre-ducarne** [comment] 2024-01-11 11:15
For me it's the opposite

**Comment by harshbytes9026** [comment] 2024-01-11 11:47
> For me it's the opposite

+1

**Comment by GolliAch** [comment] 2024-01-11 11:49
@alexandre-ducarne  opposite as working on iOS not Android?

**Comment by mrousavy** [comment] 2024-01-11 15:37
Sorry there's so much conflicting information here. My thoughts:

1. iOS never had those issues, and currently still doesn't. @anuragkaushik10 you're saying you have a blackscreen on iOS - which device did you test on? Please test the example app here.
2. @alexandre-ducarne @harshbytes9026 you're saying you are still experiencing blackscreens on Android even after upgrading to 3.7.0. - can you reproduce those in the example app? Please create a reproduction and share your `adb logcat` logs with me.
3. @maksimLobachevskiy you (+2 upvoters) are saying the issue is fixed in 3.7.0 - that's great to hear. I also found the issue to be fixed on my end.
4. @anuragkaushik10 the "Relevant Logs" are wrong. These are not adb logcat logs. Please share the full ADB logcat logs (on a gist), I can't do anything with the logs you gave me.

**Comment by Amberevol** [comment] 2024-01-12 09:15
![Screenshot_20240112_144406](https://github.com/mrousavy/react-native-vision-camera/assets/117064129/55e1e882-3827-4476-b81a-c36cd729efa7)
I'm getting this black screen on few devices android using v3.7.0

**Comment by alexandre-ducarne** [comment] 2024-01-12 14:19
@mrousavy Actually I got both working, the black screen was caused because the Android Camera permission wasn't requested beforehand. Before 3.7.0 I had issues on IOS but since that version everything is fine on both Android & IOS.

**Comment by mrousavy** [comment] 2024-01-30 16:24
> I'm getting this black screen on few devices android using v3.7.0

What? I can literally see the Camera

**Comment by mrousavy** [comment] 2024-01-30 16:25
> @mrousavy Actually I got both working, the black screen was caused because the Android Camera permission wasn't requested beforehand. Before 3.7.0 I had issues on IOS but since that version everything is fine on both Android & IOS.

Great to hear! Let's close this issue then.

**Closed as completed by mrousavy** 2024-01-30 16:25 UTC
Labels: 🐛 bug

**Comment by Amberevol** [comment] 2024-01-31 10:59
@mrousavy I can also see the camera but as you can see it is very dark and i can confirm by default camera app of my phone that, it's crystal clear and physical camera lens has no issues
