### ISSUE TITLE
java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface! 🐛 

### ISSUE THREAD

**Issue by Jitanshu06** [cuvent/react-native-vision-camera#1934] opened 2023-10-05 18:45 UTC
### What's happening?

First of all its not a duplicate issue. I earlier faced the switching camera issue with same error but that fixed with adding "key" attribute, thanks for that. 
What's happening in my case is I am having a adding attachment button on my camera screen which uses `react-native-document-picker` to pick files, Now if I click the add attachment button, it opens up the file manager to pick the file and once i click on any file it crashes the app with above error meesage. 
Initially I thought its some error from `react-native-document-picker` but when I tried it somewhere else in the app, it worked absolutely fine. Then I came to a conclusion that it definitely an error somewhat like switching camera as I faced the same error message

### Reproduceable Code

```tsx

useEffect(() => {
        const devices = Camera.getAvailableCameraDevices()
        const deviceR = getCameraDevice(devices, 'back', {
            physicalDevices: ['wide-angle-camera']
        })
        const deviceF = getCameraDevice(devices, 'front', {
            physicalDevices: ['wide-angle-camera']
        })
        setRearCamera(deviceR)
        setFrontCamera(deviceF)
    }, [])
    
const handleDocumentPick = async () => {
        try {
            const result = await DocumentPicker.pick({
                presentationStyle: "formSheet",
                copyTo: 'cachesDirectory',
            })
            console.log("🚀 ~ file: index.tsx:383 ~ handleDocumentPick ~ result:", result)
            navigation.goBack();
        } catch (error) {
            console.log("🚀 ~ file: index.tsx:384 ~ handleDocumentPick ~ error:", error)
        }
    }

//Camera Code

<Camera
     ref={camera}
     key={deviceState === DEVICE_STATE.REAR ? rearCamera.id : frontCamera.id}
     style={{ alignItems: "center", flex: 1, position: "absolute", top: 0, bottom: 0, left: 0, right: 0, zIndex: -2 }}
     device={deviceState === DEVICE_STATE.REAR ? rearCamera : frontCamera}
     photo
     video={true}
     orientation="portrait"
     isActive={isFocused}
/>
```

### Relevant log output

```shell
FATAL EXCEPTION: mrousavy/VisionCamera.main
                                                                                                   Process: com.gravhlmobileapp, PID: 12011
                                                                                                    java.lang.IllegalArgumentException: CaptureRequest contains unconfigured Input/Output Surface!
                                                                                                    	at android.hardware.camera2.CaptureRequest.convertSurfaceToStreamId(CaptureRequest.java:765)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1259)
                                                                                                    	at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1315)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:313)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.updateRepeatingRequest(CameraSession.kt:574)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.startRunning(CameraSession.kt:552)
                                                                                                    	at com.mrousavy.camera.core.CameraSession.access$startRunning(CameraSession.kt:49)
                                                                                                    	at com.mrousavy.camera.core.CameraSession$configureSession$1.invokeSuspend(CameraSession.kt:167)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8f8d4d4, mrousavy/VisionCamera.main]
```

### Camera Device

```json
{
    "id": "0",
    "position": "back",
    "hasTorch": false,
    "hasFlash": false,
    "name": "BACK (0)",
    "isMultiCam": false,
    "supportsRawCapture": false,
    "supportsFocus": true,
    "physicalDevices": [
        "telephoto-camera"
    ],
    "neutralZoom": 1,
    "supportsLowLightBoost": false,
    "minZoom": 1,
    "maxZoom": 10,
    "hardwareLevel": "limited",
    "sensorOrientation": "landscape-right",
    "formats": [
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 480,
            "videoWidth": 640,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 288,
            "videoWidth": 352,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 240,
            "videoWidth": 320,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 144,
            "videoWidth": 176,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 720,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 640,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 480,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 352,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 288,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 320,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 240,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 176,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 144,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 720,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        },
        {
            "maxFps": 30,
            "fieldOfView": 35.48934190849526,
            "photoWidth": 1280,
            "videoHeight": 960,
            "videoWidth": 1280,
            "minFps": 1,
            "minISO": 0,
            "maxISO": 0,
            "supportsDepthCapture": false,
            "supportsVideoHDR": false,
            "photoHeight": 960,
            "supportsPhotoHDR": false,
            "autoFocusSystem": "contrast-detection",
            "videoStabilizationModes": [
                "off",
                "off"
            ],
            "pixelFormats": [
                "yuv",
                "native"
            ]
        }
    ]
}
```

### Device

Emulator - API 33

### VisionCamera Version

3.2.2

### Can you reproduce this issue in the VisionCamera Example app?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I have enabled Frame Processors (react-native-worklets-core)
- [X] I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment] 2023-10-06 09:52
> First of all its not a duplicate issue

Why not?

> fixed with adding "key" attribute

This is NOT a fix. That is a hacky workaround but doesn't really solve the issue, and this is slow as well.

> I faced the same error message

Duplicate of #1773 and #1925 then.

**Closed as not planned by mrousavy** 2023-10-06 09:52 UTC
Labels: 🐛 bug
